version: "3.7"
services:
  websocket:
    container_name: pathfinder-websocket
    build:
      context: docker/websocket
      dockerfile:
        Dockerfile
  php-fpm:
    container_name: pathfinder-php-fpm
    build:
      context: .
      dockerfile:
        docker/php/Dockerfile
    volumes:
      - ./:/opt/pathfinder
      - /opt/pathfinder/node_modules
      - /opt/pathfinder/vendor
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    links:
      - mysql
      - redis
    ports:
      - 9000:9000
  nginx:
    container_name: pathfinder-nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    links:
      - websocket
      - php-fpm
    ports:
      - 3000:3000
    volumes:
      - ./docker/nginx/nginx-conf.nginx:/etc/nginx/nginx.conf
      - ./docker/nginx/pathfinder.nginx:/etc/nginx/conf.d/default.conf
      - ./:/opt/pathfinder
  mysql:
    container_name: pathfinder-mysql
    image: mysql:5.7
    volumes:
      - ./docker/mysql/charset.cnf:/etc/mysql/conf.d/charset.cnf
      - ./docker/mysql/01_init.sql:/docker-entrypoint-initdb.d/01_init.sql
#      - ./docker/mysql/02_eve_universe.sql:/docker-entrypoint-initdb.d/02_eve_universe.sql
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
  redis:
    container_name: pathfinder-redis
    image: redis:5.0.6-alpine
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--appendonly yes"]

volumes:
  mysql_data:
  redis_data:
